obstacle_range: 2.5
raytrace_range: 3.0
footprint: [[0.6, -0.25], [0.6, 0.25], [-0.6, 0.25], [-0.6, -0.25]]
#robot_radius: ir_of_robot
inflation_radius: 0.8

observation_sources: laser_scan_sensor 

laser_scan_sensor: {sensor_frame: base_laser, data_type: LaserScan, topic: scan, marking: true, clearing: true}
